version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_USER
      - SMTP_PASS
      - CONTACT_EMAIL